#!/bin/bash

echo "Starting multi-arch build process ..."
docker buildx build \
--platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8 \
--pull \
--progress plain \
--tag $IMAGE_NAME \
--file $DOCKERFILE_PATH \
--push \
.
